import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import Navigation from "./components/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  //Podemos envolver la ruta todo el contenido dentro children contiene todo lo que se renderiza hacia abjo de nuestra ruta
  return (
    <html lang='en'>
      <title>My First app with Next.js</title>
      <body >
        <Navigation />
        {children}
      </body>
    </html>
  );
}
